version: "3.1"

services:
  web_app:
    build: .
    container_name: timesheet_webapp
    ports:
      - 8080:8080
    working_dir: /timesheet
    depends_on:
      - mongo_database
    restart: always

  mongo_database:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - $HOME/data/springboot-mongo-data:/data/db
      - $HOME/data/springboot-mongo-bkp:/data/bkp
    restart: always